// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testProtobuf.proto

package com.tianxing.pojo;

public final class TestProtobuf {
  private TestProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface mMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tianxing.pojo.mMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string string1 = 1;</code>
     */
    java.lang.String getString1();
    /**
     * <code>string string1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getString1Bytes();

    /**
     * <code>string string2 = 2;</code>
     */
    java.lang.String getString2();
    /**
     * <code>string string2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getString2Bytes();

    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    java.util.List<java.lang.Integer> getInt1List();
    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    int getInt1Count();
    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    int getInt1(int index);

    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */
    int getMapCount();
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */
    boolean containsMap(
        java.lang.String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMap();
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapMap();
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    java.lang.String getMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.tianxing.pojo.mMessage}
   */
  public  static final class mMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tianxing.pojo.mMessage)
      mMessageOrBuilder {
    // Use mMessage.newBuilder() to construct.
    private mMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private mMessage() {
      string1_ = "";
      string2_ = "";
      int1_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private mMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              string1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              string2_ = s;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                int1_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              int1_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                int1_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                int1_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          int1_ = java.util.Collections.unmodifiableList(int1_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianxing.pojo.TestProtobuf.mMessage.class, com.tianxing.pojo.TestProtobuf.mMessage.Builder.class);
    }

    /**
     * <pre>
     *枚举类
     * </pre>
     *
     * Protobuf enum {@code com.tianxing.pojo.mMessage.enum1}
     */
    public enum enum1
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>elment1 = 0;</code>
       */
      elment1(0),
      /**
       * <code>element2 = 1;</code>
       */
      element2(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>elment1 = 0;</code>
       */
      public static final int elment1_VALUE = 0;
      /**
       * <code>element2 = 1;</code>
       */
      public static final int element2_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static enum1 valueOf(int value) {
        return forNumber(value);
      }

      public static enum1 forNumber(int value) {
        switch (value) {
          case 0: return elment1;
          case 1: return element2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<enum1>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          enum1> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<enum1>() {
              public enum1 findValueByNumber(int number) {
                return enum1.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tianxing.pojo.TestProtobuf.mMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final enum1[] VALUES = values();

      public static enum1 valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private enum1(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.tianxing.pojo.mMessage.enum1)
    }

    private int bitField0_;
    public static final int STRING1_FIELD_NUMBER = 1;
    private volatile java.lang.Object string1_;
    /**
     * <code>string string1 = 1;</code>
     */
    public java.lang.String getString1() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string1_ = s;
        return s;
      }
    }
    /**
     * <code>string string1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getString1Bytes() {
      java.lang.Object ref = string1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRING2_FIELD_NUMBER = 2;
    private volatile java.lang.Object string2_;
    /**
     * <code>string string2 = 2;</code>
     */
    public java.lang.String getString2() {
      java.lang.Object ref = string2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        string2_ = s;
        return s;
      }
    }
    /**
     * <code>string string2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getString2Bytes() {
      java.lang.Object ref = string2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        string2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT1_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> int1_;
    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getInt1List() {
      return int1_;
    }
    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    public int getInt1Count() {
      return int1_.size();
    }
    /**
     * <code>repeated int32 int1 = 3;</code>
     */
    public int getInt1(int index) {
      return int1_.get(index);
    }
    private int int1MemoizedSerializedSize = -1;

    public static final int MAP_FIELD_NUMBER = 5;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_MapEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    public java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map = 5;</code>
     */

    public java.lang.String getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getString1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, string1_);
      }
      if (!getString2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, string2_);
      }
      if (getInt1List().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(int1MemoizedSerializedSize);
      }
      for (int i = 0; i < int1_.size(); i++) {
        output.writeInt32NoTag(int1_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          5);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getString1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, string1_);
      }
      if (!getString2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, string2_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < int1_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(int1_.get(i));
        }
        size += dataSize;
        if (!getInt1List().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        int1MemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, map__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tianxing.pojo.TestProtobuf.mMessage)) {
        return super.equals(obj);
      }
      com.tianxing.pojo.TestProtobuf.mMessage other = (com.tianxing.pojo.TestProtobuf.mMessage) obj;

      boolean result = true;
      result = result && getString1()
          .equals(other.getString1());
      result = result && getString2()
          .equals(other.getString2());
      result = result && getInt1List()
          .equals(other.getInt1List());
      result = result && internalGetMap().equals(
          other.internalGetMap());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRING1_FIELD_NUMBER;
      hash = (53 * hash) + getString1().hashCode();
      hash = (37 * hash) + STRING2_FIELD_NUMBER;
      hash = (53 * hash) + getString2().hashCode();
      if (getInt1Count() > 0) {
        hash = (37 * hash) + INT1_FIELD_NUMBER;
        hash = (53 * hash) + getInt1List().hashCode();
      }
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianxing.pojo.TestProtobuf.mMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tianxing.pojo.TestProtobuf.mMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tianxing.pojo.mMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tianxing.pojo.mMessage)
        com.tianxing.pojo.TestProtobuf.mMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianxing.pojo.TestProtobuf.mMessage.class, com.tianxing.pojo.TestProtobuf.mMessage.Builder.class);
      }

      // Construct using com.tianxing.pojo.TestProtobuf.mMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        string1_ = "";

        string2_ = "";

        int1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableMap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tianxing.pojo.TestProtobuf.internal_static_com_tianxing_entity_mMessage_descriptor;
      }

      public com.tianxing.pojo.TestProtobuf.mMessage getDefaultInstanceForType() {
        return com.tianxing.pojo.TestProtobuf.mMessage.getDefaultInstance();
      }

      public com.tianxing.pojo.TestProtobuf.mMessage build() {
        com.tianxing.pojo.TestProtobuf.mMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tianxing.pojo.TestProtobuf.mMessage buildPartial() {
        com.tianxing.pojo.TestProtobuf.mMessage result = new com.tianxing.pojo.TestProtobuf.mMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.string1_ = string1_;
        result.string2_ = string2_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          int1_ = java.util.Collections.unmodifiableList(int1_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.int1_ = int1_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tianxing.pojo.TestProtobuf.mMessage) {
          return mergeFrom((com.tianxing.pojo.TestProtobuf.mMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tianxing.pojo.TestProtobuf.mMessage other) {
        if (other == com.tianxing.pojo.TestProtobuf.mMessage.getDefaultInstance()) return this;
        if (!other.getString1().isEmpty()) {
          string1_ = other.string1_;
          onChanged();
        }
        if (!other.getString2().isEmpty()) {
          string2_ = other.string2_;
          onChanged();
        }
        if (!other.int1_.isEmpty()) {
          if (int1_.isEmpty()) {
            int1_ = other.int1_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureInt1IsMutable();
            int1_.addAll(other.int1_);
          }
          onChanged();
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tianxing.pojo.TestProtobuf.mMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tianxing.pojo.TestProtobuf.mMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object string1_ = "";
      /**
       * <code>string string1 = 1;</code>
       */
      public java.lang.String getString1() {
        java.lang.Object ref = string1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getString1Bytes() {
        java.lang.Object ref = string1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder setString1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder clearString1() {
        
        string1_ = getDefaultInstance().getString1();
        onChanged();
        return this;
      }
      /**
       * <code>string string1 = 1;</code>
       */
      public Builder setString1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object string2_ = "";
      /**
       * <code>string string2 = 2;</code>
       */
      public java.lang.String getString2() {
        java.lang.Object ref = string2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          string2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getString2Bytes() {
        java.lang.Object ref = string2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          string2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string2 = 2;</code>
       */
      public Builder setString2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        string2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string2 = 2;</code>
       */
      public Builder clearString2() {
        
        string2_ = getDefaultInstance().getString2();
        onChanged();
        return this;
      }
      /**
       * <code>string string2 = 2;</code>
       */
      public Builder setString2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        string2_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> int1_ = java.util.Collections.emptyList();
      private void ensureInt1IsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          int1_ = new java.util.ArrayList<java.lang.Integer>(int1_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getInt1List() {
        return java.util.Collections.unmodifiableList(int1_);
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public int getInt1Count() {
        return int1_.size();
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public int getInt1(int index) {
        return int1_.get(index);
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public Builder setInt1(
          int index, int value) {
        ensureInt1IsMutable();
        int1_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public Builder addInt1(int value) {
        ensureInt1IsMutable();
        int1_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public Builder addAllInt1(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureInt1IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, int1_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 int1 = 3;</code>
       */
      public Builder clearInt1() {
        int1_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> map_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public boolean containsMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMap() {
        return getMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public java.lang.String getMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public java.lang.String getMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public Builder removeMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */
      public Builder putMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map = 5;</code>
       */

      public Builder putAllMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.tianxing.pojo.mMessage)
    }

    // @@protoc_insertion_point(class_scope:com.tianxing.pojo.mMessage)
    private static final com.tianxing.pojo.TestProtobuf.mMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tianxing.pojo.TestProtobuf.mMessage();
    }

    public static com.tianxing.pojo.TestProtobuf.mMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<mMessage>
        PARSER = new com.google.protobuf.AbstractParser<mMessage>() {
      public mMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new mMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<mMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<mMessage> getParserForType() {
      return PARSER;
    }

    public com.tianxing.pojo.TestProtobuf.mMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tianxing_entity_mMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tianxing_entity_mMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tianxing_entity_mMessage_MapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tianxing_entity_mMessage_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022testProtobuf.proto\022\023com.tianxing.entit" +
      "y\"\277\001\n\010mMessage\022\017\n\007string1\030\001 \001(\t\022\017\n\007strin" +
      "g2\030\002 \001(\t\022\014\n\004int1\030\003 \003(\005\0223\n\003map\030\005 \003(\0132&.co" +
      "m.tianxing.pojo.mMessage.MapEntry\032*\n\010M" +
      "apEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"" +
      "\"\n\005enum1\022\013\n\007elment1\020\000\022\014\n\010element2\020\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tianxing_entity_mMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tianxing_entity_mMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tianxing_entity_mMessage_descriptor,
        new java.lang.String[] { "String1", "String2", "Int1", "Map", });
    internal_static_com_tianxing_entity_mMessage_MapEntry_descriptor =
      internal_static_com_tianxing_entity_mMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_tianxing_entity_mMessage_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tianxing_entity_mMessage_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
