// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testentity.proto

package com.tianxing.entity;

public final class Testentity {
  private Testentity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface aaaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tianxing.entity.aaa)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string aasa = 1;</code>
     */
    java.lang.String getAasa();
    /**
     * <code>string aasa = 1;</code>
     */
    com.google.protobuf.ByteString
        getAasaBytes();

    /**
     * <code>string asddf = 2;</code>
     */
    java.lang.String getAsddf();
    /**
     * <code>string asddf = 2;</code>
     */
    com.google.protobuf.ByteString
        getAsddfBytes();

    /**
     * <code>repeated int32 asd = 3;</code>
     */
    java.util.List<java.lang.Integer> getAsdList();
    /**
     * <code>repeated int32 asd = 3;</code>
     */
    int getAsdCount();
    /**
     * <code>repeated int32 asd = 3;</code>
     */
    int getAsd(int index);

    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */
    int getAmapCount();
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */
    boolean containsAmap(
        java.lang.String key);
    /**
     * Use {@link #getAmapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAmap();
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAmapMap();
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    java.lang.String getAmapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    java.lang.String getAmapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.tianxing.entity.aaa}
   */
  public  static final class aaa extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.tianxing.entity.aaa)
      aaaOrBuilder {
    // Use aaa.newBuilder() to construct.
    private aaa(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private aaa() {
      aasa_ = "";
      asddf_ = "";
      asd_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private aaa(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              aasa_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              asddf_ = s;
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                asd_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              asd_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                asd_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                asd_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                amap_ = com.google.protobuf.MapField.newMapField(
                    AmapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              amap__ = input.readMessage(
                  AmapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              amap_.getMutableMap().put(
                  amap__.getKey(), amap__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          asd_ = java.util.Collections.unmodifiableList(asd_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAmap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tianxing.entity.Testentity.aaa.class, com.tianxing.entity.Testentity.aaa.Builder.class);
    }

    /**
     * <pre>
     *枚举类
     * </pre>
     *
     * Protobuf enum {@code com.tianxing.entity.aaa.asdds}
     */
    public enum asdds
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ASD = 0;</code>
       */
      ASD(0),
      /**
       * <code>ASF = 1;</code>
       */
      ASF(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ASD = 0;</code>
       */
      public static final int ASD_VALUE = 0;
      /**
       * <code>ASF = 1;</code>
       */
      public static final int ASF_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static asdds valueOf(int value) {
        return forNumber(value);
      }

      public static asdds forNumber(int value) {
        switch (value) {
          case 0: return ASD;
          case 1: return ASF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<asdds>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          asdds> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<asdds>() {
              public asdds findValueByNumber(int number) {
                return asdds.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tianxing.entity.Testentity.aaa.getDescriptor().getEnumTypes().get(0);
      }

      private static final asdds[] VALUES = values();

      public static asdds valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private asdds(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.tianxing.entity.aaa.asdds)
    }

    private int bitField0_;
    public static final int AASA_FIELD_NUMBER = 1;
    private volatile java.lang.Object aasa_;
    /**
     * <code>string aasa = 1;</code>
     */
    public java.lang.String getAasa() {
      java.lang.Object ref = aasa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aasa_ = s;
        return s;
      }
    }
    /**
     * <code>string aasa = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAasaBytes() {
      java.lang.Object ref = aasa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aasa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASDDF_FIELD_NUMBER = 2;
    private volatile java.lang.Object asddf_;
    /**
     * <code>string asddf = 2;</code>
     */
    public java.lang.String getAsddf() {
      java.lang.Object ref = asddf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asddf_ = s;
        return s;
      }
    }
    /**
     * <code>string asddf = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAsddfBytes() {
      java.lang.Object ref = asddf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asddf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASD_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> asd_;
    /**
     * <code>repeated int32 asd = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getAsdList() {
      return asd_;
    }
    /**
     * <code>repeated int32 asd = 3;</code>
     */
    public int getAsdCount() {
      return asd_.size();
    }
    /**
     * <code>repeated int32 asd = 3;</code>
     */
    public int getAsd(int index) {
      return asd_.get(index);
    }
    private int asdMemoizedSerializedSize = -1;

    public static final int AMAP_FIELD_NUMBER = 5;
    private static final class AmapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_AmapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> amap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAmap() {
      if (amap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AmapDefaultEntryHolder.defaultEntry);
      }
      return amap_;
    }

    public int getAmapCount() {
      return internalGetAmap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    public boolean containsAmap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAmap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAmapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAmap() {
      return getAmapMap();
    }
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAmapMap() {
      return internalGetAmap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    public java.lang.String getAmapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAmap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; amap = 5;</code>
     */

    public java.lang.String getAmapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAmap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getAasaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aasa_);
      }
      if (!getAsddfBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, asddf_);
      }
      if (getAsdList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(asdMemoizedSerializedSize);
      }
      for (int i = 0; i < asd_.size(); i++) {
        output.writeInt32NoTag(asd_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAmap(),
          AmapDefaultEntryHolder.defaultEntry,
          5);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAasaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aasa_);
      }
      if (!getAsddfBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, asddf_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < asd_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(asd_.get(i));
        }
        size += dataSize;
        if (!getAsdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        asdMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAmap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        amap__ = AmapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, amap__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tianxing.entity.Testentity.aaa)) {
        return super.equals(obj);
      }
      com.tianxing.entity.Testentity.aaa other = (com.tianxing.entity.Testentity.aaa) obj;

      boolean result = true;
      result = result && getAasa()
          .equals(other.getAasa());
      result = result && getAsddf()
          .equals(other.getAsddf());
      result = result && getAsdList()
          .equals(other.getAsdList());
      result = result && internalGetAmap().equals(
          other.internalGetAmap());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AASA_FIELD_NUMBER;
      hash = (53 * hash) + getAasa().hashCode();
      hash = (37 * hash) + ASDDF_FIELD_NUMBER;
      hash = (53 * hash) + getAsddf().hashCode();
      if (getAsdCount() > 0) {
        hash = (37 * hash) + ASD_FIELD_NUMBER;
        hash = (53 * hash) + getAsdList().hashCode();
      }
      if (!internalGetAmap().getMap().isEmpty()) {
        hash = (37 * hash) + AMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAmap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tianxing.entity.Testentity.aaa parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianxing.entity.Testentity.aaa parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tianxing.entity.Testentity.aaa parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tianxing.entity.Testentity.aaa parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tianxing.entity.Testentity.aaa prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tianxing.entity.aaa}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tianxing.entity.aaa)
        com.tianxing.entity.Testentity.aaaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAmap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAmap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tianxing.entity.Testentity.aaa.class, com.tianxing.entity.Testentity.aaa.Builder.class);
      }

      // Construct using com.tianxing.entity.Testentity.aaa.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        aasa_ = "";

        asddf_ = "";

        asd_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableAmap().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tianxing.entity.Testentity.internal_static_com_tianxing_entity_aaa_descriptor;
      }

      public com.tianxing.entity.Testentity.aaa getDefaultInstanceForType() {
        return com.tianxing.entity.Testentity.aaa.getDefaultInstance();
      }

      public com.tianxing.entity.Testentity.aaa build() {
        com.tianxing.entity.Testentity.aaa result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tianxing.entity.Testentity.aaa buildPartial() {
        com.tianxing.entity.Testentity.aaa result = new com.tianxing.entity.Testentity.aaa(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.aasa_ = aasa_;
        result.asddf_ = asddf_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          asd_ = java.util.Collections.unmodifiableList(asd_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.asd_ = asd_;
        result.amap_ = internalGetAmap();
        result.amap_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tianxing.entity.Testentity.aaa) {
          return mergeFrom((com.tianxing.entity.Testentity.aaa)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tianxing.entity.Testentity.aaa other) {
        if (other == com.tianxing.entity.Testentity.aaa.getDefaultInstance()) return this;
        if (!other.getAasa().isEmpty()) {
          aasa_ = other.aasa_;
          onChanged();
        }
        if (!other.getAsddf().isEmpty()) {
          asddf_ = other.asddf_;
          onChanged();
        }
        if (!other.asd_.isEmpty()) {
          if (asd_.isEmpty()) {
            asd_ = other.asd_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAsdIsMutable();
            asd_.addAll(other.asd_);
          }
          onChanged();
        }
        internalGetMutableAmap().mergeFrom(
            other.internalGetAmap());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tianxing.entity.Testentity.aaa parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tianxing.entity.Testentity.aaa) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object aasa_ = "";
      /**
       * <code>string aasa = 1;</code>
       */
      public java.lang.String getAasa() {
        java.lang.Object ref = aasa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          aasa_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string aasa = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAasaBytes() {
        java.lang.Object ref = aasa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aasa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string aasa = 1;</code>
       */
      public Builder setAasa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        aasa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string aasa = 1;</code>
       */
      public Builder clearAasa() {
        
        aasa_ = getDefaultInstance().getAasa();
        onChanged();
        return this;
      }
      /**
       * <code>string aasa = 1;</code>
       */
      public Builder setAasaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        aasa_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object asddf_ = "";
      /**
       * <code>string asddf = 2;</code>
       */
      public java.lang.String getAsddf() {
        java.lang.Object ref = asddf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asddf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asddf = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAsddfBytes() {
        java.lang.Object ref = asddf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asddf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asddf = 2;</code>
       */
      public Builder setAsddf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asddf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string asddf = 2;</code>
       */
      public Builder clearAsddf() {
        
        asddf_ = getDefaultInstance().getAsddf();
        onChanged();
        return this;
      }
      /**
       * <code>string asddf = 2;</code>
       */
      public Builder setAsddfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        asddf_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> asd_ = java.util.Collections.emptyList();
      private void ensureAsdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          asd_ = new java.util.ArrayList<java.lang.Integer>(asd_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getAsdList() {
        return java.util.Collections.unmodifiableList(asd_);
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public int getAsdCount() {
        return asd_.size();
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public int getAsd(int index) {
        return asd_.get(index);
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public Builder setAsd(
          int index, int value) {
        ensureAsdIsMutable();
        asd_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public Builder addAsd(int value) {
        ensureAsdIsMutable();
        asd_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public Builder addAllAsd(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAsdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, asd_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 asd = 3;</code>
       */
      public Builder clearAsd() {
        asd_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> amap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAmap() {
        if (amap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AmapDefaultEntryHolder.defaultEntry);
        }
        return amap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAmap() {
        onChanged();;
        if (amap_ == null) {
          amap_ = com.google.protobuf.MapField.newMapField(
              AmapDefaultEntryHolder.defaultEntry);
        }
        if (!amap_.isMutable()) {
          amap_ = amap_.copy();
        }
        return amap_;
      }

      public int getAmapCount() {
        return internalGetAmap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public boolean containsAmap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAmap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAmapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAmap() {
        return getAmapMap();
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAmapMap() {
        return internalGetAmap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public java.lang.String getAmapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAmap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public java.lang.String getAmapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAmap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAmap() {
        internalGetMutableAmap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public Builder removeAmap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAmap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAmap() {
        return internalGetMutableAmap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */
      public Builder putAmap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAmap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; amap = 5;</code>
       */

      public Builder putAllAmap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAmap().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.tianxing.entity.aaa)
    }

    // @@protoc_insertion_point(class_scope:com.tianxing.entity.aaa)
    private static final com.tianxing.entity.Testentity.aaa DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tianxing.entity.Testentity.aaa();
    }

    public static com.tianxing.entity.Testentity.aaa getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<aaa>
        PARSER = new com.google.protobuf.AbstractParser<aaa>() {
      public aaa parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new aaa(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<aaa> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<aaa> getParserForType() {
      return PARSER;
    }

    public com.tianxing.entity.Testentity.aaa getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tianxing_entity_aaa_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tianxing_entity_aaa_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tianxing_entity_aaa_AmapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tianxing_entity_aaa_AmapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020testentity.proto\022\023com.tianxing.entity\"" +
      "\251\001\n\003aaa\022\014\n\004aasa\030\001 \001(\t\022\r\n\005asddf\030\002 \001(\t\022\013\n\003" +
      "asd\030\003 \003(\005\0220\n\004amap\030\005 \003(\0132\".com.tianxing.e" +
      "ntity.aaa.AmapEntry\032+\n\tAmapEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\031\n\005asdds\022\007\n\003ASD" +
      "\020\000\022\007\n\003ASF\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tianxing_entity_aaa_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tianxing_entity_aaa_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tianxing_entity_aaa_descriptor,
        new java.lang.String[] { "Aasa", "Asddf", "Asd", "Amap", });
    internal_static_com_tianxing_entity_aaa_AmapEntry_descriptor =
      internal_static_com_tianxing_entity_aaa_descriptor.getNestedTypes().get(0);
    internal_static_com_tianxing_entity_aaa_AmapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tianxing_entity_aaa_AmapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
